-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelHw where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsHw

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsHw.Ident -> Result
transIdent x = case x of
  AbsHw.Ident string -> failure x

transExp :: AbsHw.Exp -> Result
transExp x = case x of
  AbsHw.EAbs ident exp -> failure x
  AbsHw.EApp exp1 exp2 -> failure x
  AbsHw.EVar ident -> failure x
