-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language numbers.

module AbsNumbers where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp
    = Plus Exp Exp
    | Minus Exp Exp
    | IntDivision Exp Exp
    | Modulus Exp Exp
    | Times Exp Exp
    | Num Integer
    | Exponent Exp Exp
    | Negative Exp
    | Paranth Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

